// src/routes/product/[...slug].tsx
import { MockupProduct } from 'constants/Types/Products.types';
import { useParams } from 'solid-start';
import { ProductDetails } from '~/components/Product/Details';

const mockup: MockupProduct = {
    slug: 'celesteia',
    title: 'Celesteia',
    description:
        "Humankind's last hope spreads across the galaxy to rebuild humanity's glory.",
    logo: 'https://raw.githubusercontent.com/leafal-io/celesteia/production/Icon.bmp',
    thumbnail:
        'https://raw.githubusercontent.com/leafal-io/celesteia/production/img/thumbnail.jpg',
    background:
        'https://raw.githubusercontent.com/leafal-io/celesteia/production/img/background.jpg',
};

export function ProductPage() {
    const _params = useParams();
    return <ProductDetails product={mockup} />;
}

// src/routes/profile/[slug]/index.tsx
import { Show, createEffect, createSignal } from 'solid-js';
import { Title, useParams } from 'solid-start';
import { MainWrapper } from '~/components/Layout/MainWrapper';
import { PageBackdrop } from '~/components/Layout/PageBackdrop';
import { getPublicProfile } from '~/components/User';
import { ProfileContainer } from '~/components/User/Profiles/Container';
import { TPublicUserRecord } from '~/library/Types/User.types';

export type ProfileProps = {
    slug: string;
};

export default function ProfilePage() {
    const { slug } = useParams<{ slug: string }>();

    const [user, setUser] = createSignal<TPublicUserRecord | undefined | null>(
        undefined
    );

    createEffect(() => getPublicProfile(slug).then((res) => setUser(res)));

    const resolvedUser = () => user() as TPublicUserRecord;
    const pageTitle = () =>
        `${
            resolvedUser().profile.displayname || resolvedUser().username
        } - leafal.io`;

    return (
        <>
            <Show when={user() === null}>
                <Title>{'User not found - leafal.io'}</Title>

                <MainWrapper>
                    <span>User not found</span>
                </MainWrapper>
            </Show>

            <Show when={user()}>
                <Title>{pageTitle()}</Title>

                <PageBackdrop
                    src={`https://raw.githubusercontent.com/leafal-io/celesteia/production/img/background.jpg`}
                >
                    <MainWrapper>
                        <ProfileContainer user={resolvedUser()} />
                    </MainWrapper>
                </PageBackdrop>
            </Show>
        </>
    );
}
